apiVersion: v1
kind: Service
metadata:
  name: pokemon-web-main
spec:
  selector:
    app: pokemon-web-main
  ports:
    - port: 8080
      nodePort: 30020
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-web
spec:
  selector:
    app: mysql-web-main
  ports:
    - port: 3306
      nodePort: 30021
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
  type: ClusterIP

